import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Briefcase, Code, Mail, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="relative overflow-hidden">
          {/* {renderCurrentSection()} */}

          {/* macOS-style Dock Navigation */}
          <nav className="fixed bottom-2 md:bottom-4 left-1/2 transform -translate-x-1/2 z-50">
            <div className="bg-white/10 backdrop-blur-lg rounded-xl md:rounded-2xl p-1 md:p-2 border border-white/20 shadow-2xl">
              <div className="flex items-center gap-1 md:gap-2">
                <button
                  className={`p-2 md:p-3 rounded-lg md:rounded-xl transition-all duration-300 hover:scale-110 touch-manipulation cursor-pointer`}
                  title="About"
                >
                  <User className="w-5 h-5 md:w-6 md:h-6 text-white" />
                </button>
                <button
                  className={`p-2 md:p-3 rounded-lg md:rounded-xl transition-all duration-300 hover:scale-110 touch-manipulation cursor-pointer`}
                  title="Skills"
                >
                  <Code className="w-5 h-5 md:w-6 md:h-6 text-white" />
                </button>
                <button
                  className={`p-2 md:p-3 rounded-lg md:rounded-xl transition-all duration-300 hover:scale-110 touch-manipulation cursor-pointer`}
                  title="Projects"
                >
                  <Briefcase className="w-5 h-5 md:w-6 md:h-6 text-white" />
                </button>
                <button
                  className={`p-2 md:p-3 rounded-lg md:rounded-xl transition-all duration-300 hover:scale-110 touch-manipulation cursor-pointer`}
                  title="Contact"
                >
                  <Mail className="w-5 h-5 md:w-6 md:h-6 text-white" />
                </button>
              </div>
            </div>
          </nav>
        </div>
      </body>
    </html>
  );
}
